liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/ViewModels/DateToStringVM.swift, liveOn/liveOn/Views/Voicemail/VoicemailView.swift
보이스메일 view 만들었고, 
대부분 페이지마다 날짜 들어갈텐데 
date형 instance를 저희가 원하는 형태(ex. 220604)의 string으로 바꾸는 
DateToString 함수 만들었습니다
=> [Feat] voicemail view & date to string VM created

liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift
- 템플릿 테스트 및 PhotoCardView 뒤로가기 기능 수정
=> [Fix] PhotoCard 뒤로가기 기능

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/ViewModels/DateToStringVM.swift, liveOn/liveOn/Views/ContentView.swift, liveOn/liveOn/Views/GiftBoxView.swift, liveOn/liveOn/Views/Letter/TextLimiter.swift, liveOn/liveOn/Views/SignIn/GettingStartView.swift, liveOn/liveOn/Views/SignIn/SelectWhatToDoView.swift, liveOn/liveOn/Views/SignIn/SetBirthdayView.swift, liveOn/liveOn/Views/SignIn/SetFirstDayView.swift, liveOn/liveOn/Views/SignIn/SetNicknameView.swift, liveOn/liveOn/Views/SignIn/User.swift
- `Introduction`: ex) 로그인 API에서 password validation error 수정 pull request 
- `Notion Ticket`: [notion link]()
- `Figma`: [figma link]()
- 이미지 첨부
=> [Feat] Improve GettingStart

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Views/CreateGiftListView.swift, liveOn/liveOn/Views/Flower/Flower.swift, liveOn/liveOn/Views/Flower/FlowerListView.swift, liveOn/liveOn/Views/Flower/FlowerView.swift, liveOn/liveOn/Views/Pill/Pill.swift, liveOn/liveOn/Views/Pill/PillListView.swift, liveOn/liveOn/Views/Pill/PillView.swift
- `Introduction`: 영양제 선물 제작뷰 & 꽃 선물 제작 뷰의 UI 작업을 Develop 브랜치와 합치게 됩니다.
- Seperate class Flower and class Pill definition to Flower.swift and Pill.swift file
- Replace FlowerHeaderView with NavigationTitle at FlowerView
- Add variables to FlowerView
- Replace PillHeaderView with modifiers
- Delete FlowerHeaderView
- Align text counter to the trailing side inside PillView
- Change color of BarUnderTextField inside PillView
- Create RoundedRectangle under "탭해서 다른 약으로 바꾸기" inside PillView
- Replace multilineTextAlignment modifier with frame inside FlowerView
- Replace RoundedRectangle with Image("flower") inside FlowerView
- Create FlowerListView & PillListView
=> [Feat] 영양제 선물 제작뷰 & 꽃 선물 제작 뷰의 UI 작업

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Models/Recording.swift, liveOn/liveOn/ViewModels/DateToStringVM.swift, liveOn/liveOn/ViewModels/VoiceRecorderVM.swift, liveOn/liveOn/Views/CreateGiftListView.swift, liveOn/liveOn/Views/Voicemail/VoicemailMainView.swift, liveOn/liveOn/Views/Voicemail/VoicemailView.swift
- Voicemail View Completed
- Voicemail View Refactored
- 이미지 첨부
=> [Feat] Voicemail View Completed & [Refactor] Voicemail View Refactored

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/ViewModels/QuickSignInWithApple.swift, liveOn/liveOn/ViewModels/SignInWithAppleViewModel.swift, liveOn/liveOn/Views/SignIn/GettingStartView.swift, liveOn/liveOn/liveOn.entitlements
- SigninwithApple을 위한 준비를 했습니다. (상세 구현 X)
=> [Feat] Create sign in with apple View

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Extensions/ConvertSecToMinAndHour.swift, liveOn/liveOn/ViewModels/VoiceRecorderVM.swift, liveOn/liveOn/Views/CreateGiftListView.swift, liveOn/liveOn/Views/Voicemail/VoicemailCassetteView.swift, liveOn/liveOn/Views/Voicemail/VoicemailView.swift
=> [Fix] Removed voicemail restored

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/ViewModels/imageViewModel.swift, liveOn/liveOn/Views/ContentView.swift, liveOn/liveOn/Views/CreateGiftListView.swift, liveOn/liveOn/Views/GiftBoxView.swift, liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift, liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift, liveOn/liveOn/Views/SignIn/SelectWhatToDoView.swift
- 달력뷰에서 기념일 추가를 취소할시, 사진 선물하기에서 사진 업로드시 맨 처음 getting start View로 돌아오는 현상을 해결했습니다. 
ContentView에서 navigationView가 중복으로 걸려있던 것이 삭제되었고, GiftBox에 navigationView가 새롭게 추가되었습니다.
=> Fix: GettingStartView로 돌아오는 현상 해결

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Views/CreateGiftListView.swift, liveOn/liveOn/Views/Flower/FlowerDetailView.swift, liveOn/liveOn/Views/GiftBoxView.swift
- `Introduction` : 받은 꽃 리스트 뷰와 달력에서 보여지는 그날의 선물 목록에서 보여지는 꽃의 정보를 보여주는 FlowerDetailView를 생성하고, 밀리의 리버트로 인해 날아갔던 작은 것들을 되살립니다.
`FlowerDetailView`
- Create FlowerDetailView.swift
- Create Pop Up window that shows information of the flower that has been clicked
`etc`
- Set Flower.swift & FlowerListView.swift Target Membership to liveOn
- Set NavigationLink inside GiftBoxView to FlowerListView
- Set createItemView to FlowerView()
=> [Feat] Create Flower PopUp Window + etc

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/ViewModels/VoiceRecorderVM.swift, liveOn/liveOn/Views/Calendar/CalendarBack.swift, liveOn/liveOn/Views/Calendar/CalendarMain.swift, liveOn/liveOn/Views/Calendar/MoveDateButton.swift, liveOn/liveOn/Views/Calendar/MoveDatePicker.swift, liveOn/liveOn/Views/Flower/FlowerListView.swift, liveOn/liveOn/Views/Flower/FlowerPopUpView.swift
-  <img width="346" alt="image" src="https://user-images.githubusercontent.com/103008077/173499262-903394bb-3100-47f3-8925-04f2253b87d0.png">
=> [feat] Add MoveDatePicker Button

liveOn/liveOn/Views/Flower/FlowerListView.swift, liveOn/liveOn/Views/Flower/FlowerPopUpView.swift, liveOn/liveOn/Views/Flower/FlowerView.swift
- `Introduction`: FlowerListView를 디자인한 화면과 같을 수 있도록 요소들을 추가 + 수정합니다.
- alert를 삭제
- FlowerListView 상단과 하단에 글을 추가
=> [Fix] Enhance FlowerListView + etc

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Models/ServerCommunication.swift, liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift, liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift
- [Feat] Fix Compile Source Error in Xcode
=> [Feat] Fix Compile Source Error in Xcode

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Etc/NetworkLoggerPlugin.swift, liveOn/liveOn/Models/ServerCommunication.swift, liveOn/liveOn/ViewModels/ServerCommunicationVM.swift, liveOn/liveOn/ViewModels/VoiceRecorderVM.swift, liveOn/liveOn/Views/Voicemail/VoicemailView.swift
- Added server communication
- Voicemail, Get request fin.
- others (image upload, login) needs test
=> [Feat] Server Communication added (Voicemail, Get fin.)

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Extensions/BackButtonExtension.swift, liveOn/liveOn/ViewModels/imageViewModel.swift, liveOn/liveOn/Views/Calendar/CalendarMain.swift, liveOn/liveOn/Views/Calendar/MoveDatePicker.swift, liveOn/liveOn/Views/Calendar/PlusSetting.swift, liveOn/liveOn/Views/CoupleInformation/CoupleInformation.swift, liveOn/liveOn/Views/CoupleInformation/DetailedInformationView.swift, liveOn/liveOn/Views/CreateGiftListView.swift, liveOn/liveOn/Views/Flower/FlowerListView.swift, liveOn/liveOn/Views/Flower/FlowerPopUpView.swift, liveOn/liveOn/Views/GiftBoxView.swift, liveOn/liveOn/Views/Letter/LetterListView.swift, liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift, liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift, liveOn/liveOn/Views/Pill/PillListView.swift, liveOn/liveOn/Views/SignIn/GettingStartView.swift, liveOn/liveOn/Views/SignIn/SelectWhatToDoView.swift, liveOn/liveOn/Views/SignIn/SetBirthdayView.swift, liveOn/liveOn/Views/SignIn/SetFirstDayView.swift
View extension을 통해 backButton 양식을 만들고, 이를 전체 View에 적용하여 backButton 양식을 통일했습니다.
=> Fix: NaviagtionBackButton Revision

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Extensions/BackButtonExtension.swift, liveOn/liveOn/Models/ServerCommunication.swift, liveOn/liveOn/Views/CoupleInformation/CoupleInformation.swift, liveOn/liveOn/Views/Flower/FlowerPopUpView.swift, liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift, liveOn/liveOn/Views/Pill/Pill.swift, liveOn/liveOn/Views/Pill/PillListView.swift
=> Feat: PillView Making

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Views/Pill/PillPopUpView.swift
=> Fix: Merge 이후 버그 수정

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, liveOn/liveOn/Models/AppleSocialLogin.swift, liveOn/liveOn/ViewModels/AuthenticationViewModel.swift, liveOn/liveOn/Views/Calendar/CalendarMain.swift, liveOn/liveOn/Views/SignIn/GettingStartView.swift
=> [feat] apple sign in

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, liveOn/liveOn/LiveOnApp.swift, liveOn/liveOn/Models/ServerCommunication.swift, liveOn/liveOn/ViewModels/ImageViewModel.swift, liveOn/liveOn/ViewModels/ServerCommunicationVM.swift, liveOn/liveOn/Views/CreateGiftListView.swift, liveOn/liveOn/Views/GiftBoxView.swift, liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift, liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift
merge 이후 conflict가 발생하여 수정하였습니다.
=> Fix: Merge 이후 버그 사항들 수정

liveOn/liveOn.xcodeproj/project.pbxproj, liveOn/liveOn/Extensions/BackButtonExtension.swift, liveOn/liveOn/Views/GiftBoxView.swift, liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift, liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift, liveOn/liveOn/Views/PictureGift/PhotoTransport.swift, liveOn/liveOn/Views/SignIn/SetBirthdayView.swift, liveOn/liveOn/Views/SignIn/SetFirstDayView.swift
- 발표를 앞두고 버그 테스팅 및 그에 따른 UI 수정 진행
=> Fix: UI 버그 수정

liveOn/liveOn/ViewModels/ServerCommunicationViewModel.swift, liveOn/liveOn/ViewModels/VoiceRecorderViewModel.swift, liveOn/liveOn/Views/Voicemail/VoicemailCassette.swift, liveOn/liveOn/Views/Voicemail/VoicemailsView.swift
=> [Fix] Merge 후 빌드에러 수정

liveOn/liveOn.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, liveOn/liveOn/Models/ServerCommunication.swift, liveOn/liveOn/Views/Calendar/CalendarMain.swift, liveOn/liveOn/Views/Calendar/PlusSetting.swift, liveOn/liveOn/Views/Flower/FlowerView.swift, liveOn/liveOn/Views/Letter/CreateLetterView.swift, liveOn/liveOn/Views/Letter/Letter.swift, liveOn/liveOn/Views/Letter/LetterListView.swift, liveOn/liveOn/Views/PictureGift/PhotoCardsView.swift, liveOn/liveOn/Views/PictureGift/PhotoGiftView.swift, liveOn/liveOn/Views/Pill/Pill.swift, liveOn/liveOn/Views/Pill/PillListView.swift, liveOn/liveOn/Views/Pill/PillPopUpView.swift, liveOn/liveOn/Views/Voicemail/VoicemailCassette.swift, liveOn/liveOn/Views/Voicemail/VoicemailsView.swift
- Back btn size changed
- Background color changed
- LetterListView popup changed
=> [Refactor] overall views refactored for sample video
